apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-catalog-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-catalog
  template:
    metadata:
      labels:
        app: product-catalog
    spec:
      containers:
        - image: vcesar0edu/rso_repo:product-catalog-2022-12-03
          name: product-catalog
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://lucky.db.elephantsql.com:5432/plqeoytw
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: plqeoytw
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elephant-pg-pwd
                  key: pg-pass
          ports:
            - containerPort: 8080
              name: server
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: product-catalog
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: product-catalog