kumuluzee:
  name: product-catalog-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  openapi-mp:
    ui:
      server-auto-config:
        enabled: true
        original-uri-check: false
  datasources:
    - jndi-name: jdbc/ProductMetadataDS
      connection-url: jdbc:postgresql://localhost:5432/rso_product
      username: dbuser_Diagnoses7782
      password: T3Bo32fu7yW#Gj^%r!%^
      max-pool-size: 20
rest-properties:
  maintenance-mode: false
  broken: false