name: Build docker image, push to DockerHub deploy to Azure K8S

on:
  push:
    branches: [ "new-release" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get time
      id: time
      uses: nanzm/get-time-action@v1.0
      with:
        timeZone: 1
        format: 'YYYY-MM-DD-HH-mm-ss'
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Set Image Tag
      id: docker_image_tag
      run: |
        tag="${{ secrets.DOCKERHUB_UNAME }}/${{ secrets.DOCKERHUB_REPONAME }}:${{ secrets.DOCKERHUB_IMG_PREFIX }}-${{ steps.time.outputs.time }}"
    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_UNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        file: ./Dockerfile_with_maven_build
        push: true
        tags: ${{ steps.docker_image_tag.tag }}
